dataset_type: loaded
dataset_dir: /p/scratch/hai_fnetwlet/datasets/loaded_65536
dataset_kwargs:
  references:
    - jsut
batch_size: 128
num_workers: 4
multiprocessing_context: spawn
persistent_workers: true
stop_epoch: 40
num_checkpoints: 1
num_validations: 20
tasks:
  - main_module: script.training.simple_cnn
    output_dir: /p/project/hai_fnetwlet/models/simple_1d_conv_jsut/1/
    model: 1d
    seed: 1
  - main_module: script.training.simple_cnn
    output_dir: /p/project/hai_fnetwlet/models/simple_1d_conv_jsut/2/
    model: 1d
    seed: 2
  - main_module: script.training.simple_cnn
    output_dir: /p/project/hai_fnetwlet/models/simple_1d_conv_jsut/3/
    model: 1d
    seed: 3
  - main_module: script.training.simple_cnn
    output_dir: /p/project/hai_fnetwlet/models/simple_1d_conv_jsut/4/
    model: 1d
    seed: 4
