dataset_type: loaded
dataset_dir: /p/scratch/hai_fnetwlet/datasets/loaded_AB_65536
dataset_kwargs:
  references:
    - jsut
batch_size: 128
num_workers: 2
pin_memory: true
persistent_workers: true
stop_epoch: 80
num_checkpoints: 3
num_validations: 40
model: 2d
lr_scheduler: true
lr_step_size: 20
wavelet: db4
tasks:
  - main_module: script.training.wide_6_1d_vs_2d
    output_dir: /p/project/hai_fnetwlet/models/Wide6_2d_JSUT/db4/1/
    seed: 1
  - main_module: script.training.wide_6_1d_vs_2d
    output_dir: /p/project/hai_fnetwlet/models/Wide6_2d_JSUT/db4/2/
    seed: 2
  - main_module: script.training.wide_6_1d_vs_2d
    output_dir: /p/project/hai_fnetwlet/models/Wide6_2d_JSUT/db4/3/
    seed: 3
  - main_module: script.training.wide_6_1d_vs_2d
    output_dir: /p/project/hai_fnetwlet/models/Wide6_2d_JSUT/db4/4/
    seed: 4
