dataset_type: loaded
dataset_dir: /p/scratch/hai_fnetwlet/datasets/loaded_AB_65536
dataset_kwargs:
  references:
    - ljspeech
  generators:
    - full_band_melgan
batch_size: 128
num_workers: 2
pin_memory: true
persistent_workers: true
stop_epoch: 40
num_checkpoints: 1
num_validations: 20
model: Wide24Basic
wavelet: haar
lr_scheduler: true
lr_milestones:
  - 10
  - 20
tasks:
  - main_module: script.training.wide_x_single
    output_dir: /p/project/hai_fnetwlet/models/wide_basic_FBM_haar/1/
    seed: 1
  - main_module: script.training.wide_x_single
    output_dir: /p/project/hai_fnetwlet/models/wide_basic_FBM_haar/2/
    seed: 2
  - main_module: script.training.wide_x_single
    output_dir: /p/project/hai_fnetwlet/models/wide_basic_FBM_haar/3/
    seed: 3
  - main_module: script.training.wide_x_single
    output_dir: /p/project/hai_fnetwlet/models/wide_basic_FBM_haar/4/
    seed: 4
